name=BMP580
version=1.0.0
author=Tomas Michal
maintainer=Tomas Michal
sentence=Arduino library for the BMP580 sensor (I2C only)
paragraph=Simple library for basic use of the Bosch BMP580 pressure and temperature sensor. This library supports only I2C communication.
category=Sensors
url=https://github.com/Tomasraketak/BMP580-library
architectures=*
includes=BMP580.h
dependencies=Wire
license=MIT
